// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package bishopbusiness is a generated GoMock package.
package bishopbusiness

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataBishopBusinessAdapter is a mock of DataBishopBusinessAdapter interface.
type MockDataBishopBusinessAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataBishopBusinessAdapterMockRecorder
}

// MockDataBishopBusinessAdapterMockRecorder is the mock recorder for MockDataBishopBusinessAdapter.
type MockDataBishopBusinessAdapterMockRecorder struct {
	mock *MockDataBishopBusinessAdapter
}

// NewMockDataBishopBusinessAdapter creates a new mock instance.
func NewMockDataBishopBusinessAdapter(ctrl *gomock.Controller) *MockDataBishopBusinessAdapter {
	mock := &MockDataBishopBusinessAdapter{ctrl: ctrl}
	mock.recorder = &MockDataBishopBusinessAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataBishopBusinessAdapter) EXPECT() *MockDataBishopBusinessAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataBishopBusinessAdapter) Create(arg0 *BishopBusiness) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataBishopBusinessAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataBishopBusinessAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataBishopBusinessAdapter) Delete(arg0 *BishopBusiness) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataBishopBusinessAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataBishopBusinessAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataBishopBusinessAdapter) Read(arg0 *BishopBusiness) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataBishopBusinessAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataBishopBusinessAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataBishopBusinessAdapter) ReadAll(arg0 *[]BishopBusiness, arg1 BishopBusinessParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataBishopBusinessAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataBishopBusinessAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataBishopBusinessAdapter) Update(arg0 BishopBusiness) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataBishopBusinessAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataBishopBusinessAdapter)(nil).Update), arg0)
}
