create table agenda (
date text,
presiding text,
conducting text,
organist text,
chorister text,
newsletter text,
invocation text,
benediction text,
ward_business boolean,
bishop_business boolean,
letter_read boolean,
stake_business boolean,
stake text,
new_members boolean,
ordinance boolean,
fast_sunday boolean,
agenda_published boolean,
program_published boolean,
opening_hymn text,
sacrament_hymn text,
closing_hymn text,
fs_musical_number text,
primary key(date)
);