insert into agenda select
date,
presiding,
conducting,
organist,
chorister,
newsletter,
invocation,
benediction,
ward_business,
bishop_business,
letter_read,
stake_business,
stake,
new_members,
ordinance,
fast_sunday,
agenda_published,
program_published,
opening_hymn,
sacrament_hymn,
closing_hymn,
fs_musical_number from temp_agenda;