create temp table temp_agenda as select
date,
presiding,
conducting,
organist,
chorister,
newsletter,
invocation,
benediction,
ward_business,
bishop_business,
letter_read,
stake_business,
stake,
new_members,
ordinance,
fast_sunday,
agenda_published,
program_published,
cast(opening_hymn as text) as opening_hymn,
cast(sacrament_hymn as text) sacrament_hymn,
cast(closing_hymn as text) closing_hymn,
fs_musical_number from agenda;