// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package roles is a generated GoMock package.
package roles

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataRolesAdapter is a mock of DataRolesAdapter interface.
type MockDataRolesAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataRolesAdapterMockRecorder
}

// MockDataRolesAdapterMockRecorder is the mock recorder for MockDataRolesAdapter.
type MockDataRolesAdapterMockRecorder struct {
	mock *MockDataRolesAdapter
}

// NewMockDataRolesAdapter creates a new mock instance.
func NewMockDataRolesAdapter(ctrl *gomock.Controller) *MockDataRolesAdapter {
	mock := &MockDataRolesAdapter{ctrl: ctrl}
	mock.recorder = &MockDataRolesAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRolesAdapter) EXPECT() *MockDataRolesAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataRolesAdapter) Create(arg0 *Roles) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataRolesAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataRolesAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataRolesAdapter) Delete(arg0 *Roles) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRolesAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRolesAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataRolesAdapter) Read(arg0 *Roles) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataRolesAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataRolesAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataRolesAdapter) ReadAll(arg0 *[]Roles, arg1 RolesParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataRolesAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataRolesAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataRolesAdapter) Update(arg0 Roles) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRolesAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRolesAdapter)(nil).Update), arg0)
}
