// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package role is a generated GoMock package.
package role

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataRoleAdapter is a mock of DataRoleAdapter interface.
type MockDataRoleAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataRoleAdapterMockRecorder
}

// MockDataRoleAdapterMockRecorder is the mock recorder for MockDataRoleAdapter.
type MockDataRoleAdapterMockRecorder struct {
	mock *MockDataRoleAdapter
}

// NewMockDataRoleAdapter creates a new mock instance.
func NewMockDataRoleAdapter(ctrl *gomock.Controller) *MockDataRoleAdapter {
	mock := &MockDataRoleAdapter{ctrl: ctrl}
	mock.recorder = &MockDataRoleAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRoleAdapter) EXPECT() *MockDataRoleAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataRoleAdapter) Create(arg0 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataRoleAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataRoleAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataRoleAdapter) Delete(arg0 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRoleAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRoleAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataRoleAdapter) Read(arg0 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataRoleAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataRoleAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataRoleAdapter) ReadAll(arg0 *[]Role, arg1 RoleParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataRoleAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataRoleAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataRoleAdapter) Update(arg0 Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRoleAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRoleAdapter)(nil).Update), arg0)
}
