// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package defaultcalling is a generated GoMock package.
package defaultcalling

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataDefaultCallingAdapter is a mock of DataDefaultCallingAdapter interface.
type MockDataDefaultCallingAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataDefaultCallingAdapterMockRecorder
}

// MockDataDefaultCallingAdapterMockRecorder is the mock recorder for MockDataDefaultCallingAdapter.
type MockDataDefaultCallingAdapterMockRecorder struct {
	mock *MockDataDefaultCallingAdapter
}

// NewMockDataDefaultCallingAdapter creates a new mock instance.
func NewMockDataDefaultCallingAdapter(ctrl *gomock.Controller) *MockDataDefaultCallingAdapter {
	mock := &MockDataDefaultCallingAdapter{ctrl: ctrl}
	mock.recorder = &MockDataDefaultCallingAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDefaultCallingAdapter) EXPECT() *MockDataDefaultCallingAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataDefaultCallingAdapter) Create(arg0 *DefaultCalling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataDefaultCallingAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataDefaultCallingAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataDefaultCallingAdapter) Delete(arg0 *DefaultCalling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataDefaultCallingAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataDefaultCallingAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataDefaultCallingAdapter) Read(arg0 *DefaultCalling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataDefaultCallingAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataDefaultCallingAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataDefaultCallingAdapter) ReadAll(arg0 *[]DefaultCalling, arg1 DefaultCallingParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataDefaultCallingAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataDefaultCallingAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataDefaultCallingAdapter) Update(arg0 DefaultCalling) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataDefaultCallingAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataDefaultCallingAdapter)(nil).Update), arg0)
}
