// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package newmember is a generated GoMock package.
package newmember

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataNewMemberAdapter is a mock of DataNewMemberAdapter interface.
type MockDataNewMemberAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataNewMemberAdapterMockRecorder
}

// MockDataNewMemberAdapterMockRecorder is the mock recorder for MockDataNewMemberAdapter.
type MockDataNewMemberAdapterMockRecorder struct {
	mock *MockDataNewMemberAdapter
}

// NewMockDataNewMemberAdapter creates a new mock instance.
func NewMockDataNewMemberAdapter(ctrl *gomock.Controller) *MockDataNewMemberAdapter {
	mock := &MockDataNewMemberAdapter{ctrl: ctrl}
	mock.recorder = &MockDataNewMemberAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataNewMemberAdapter) EXPECT() *MockDataNewMemberAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataNewMemberAdapter) Create(arg0 *NewMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataNewMemberAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataNewMemberAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataNewMemberAdapter) Delete(arg0 *NewMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataNewMemberAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataNewMemberAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataNewMemberAdapter) Read(arg0 *NewMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataNewMemberAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataNewMemberAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataNewMemberAdapter) ReadAll(arg0 *[]NewMember, arg1 NewMemberParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataNewMemberAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataNewMemberAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataNewMemberAdapter) Update(arg0 NewMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataNewMemberAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataNewMemberAdapter)(nil).Update), arg0)
}
