// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package hymn is a generated GoMock package.
package hymn

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataHymnAdapter is a mock of DataHymnAdapter interface.
type MockDataHymnAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataHymnAdapterMockRecorder
}

// MockDataHymnAdapterMockRecorder is the mock recorder for MockDataHymnAdapter.
type MockDataHymnAdapterMockRecorder struct {
	mock *MockDataHymnAdapter
}

// NewMockDataHymnAdapter creates a new mock instance.
func NewMockDataHymnAdapter(ctrl *gomock.Controller) *MockDataHymnAdapter {
	mock := &MockDataHymnAdapter{ctrl: ctrl}
	mock.recorder = &MockDataHymnAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataHymnAdapter) EXPECT() *MockDataHymnAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataHymnAdapter) Create(arg0 *Hymn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataHymnAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataHymnAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataHymnAdapter) Delete(arg0 *Hymn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataHymnAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataHymnAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataHymnAdapter) Read(arg0 *Hymn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataHymnAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataHymnAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataHymnAdapter) ReadAll(arg0 *[]Hymn, arg1 HymnParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataHymnAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataHymnAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataHymnAdapter) Update(arg0 Hymn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataHymnAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataHymnAdapter)(nil).Update), arg0)
}
