// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package wardbusinessrel is a generated GoMock package.
package wardbusinessrel

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataWardBusinessRelAdapter is a mock of DataWardBusinessRelAdapter interface.
type MockDataWardBusinessRelAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataWardBusinessRelAdapterMockRecorder
}

// MockDataWardBusinessRelAdapterMockRecorder is the mock recorder for MockDataWardBusinessRelAdapter.
type MockDataWardBusinessRelAdapterMockRecorder struct {
	mock *MockDataWardBusinessRelAdapter
}

// NewMockDataWardBusinessRelAdapter creates a new mock instance.
func NewMockDataWardBusinessRelAdapter(ctrl *gomock.Controller) *MockDataWardBusinessRelAdapter {
	mock := &MockDataWardBusinessRelAdapter{ctrl: ctrl}
	mock.recorder = &MockDataWardBusinessRelAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataWardBusinessRelAdapter) EXPECT() *MockDataWardBusinessRelAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataWardBusinessRelAdapter) Create(arg0 *WardBusinessRel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataWardBusinessRelAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataWardBusinessRelAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataWardBusinessRelAdapter) Delete(arg0 *WardBusinessRel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataWardBusinessRelAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataWardBusinessRelAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataWardBusinessRelAdapter) Read(arg0 *WardBusinessRel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataWardBusinessRelAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataWardBusinessRelAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataWardBusinessRelAdapter) ReadAll(arg0 *[]WardBusinessRel, arg1 WardBusinessRelParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataWardBusinessRelAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataWardBusinessRelAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataWardBusinessRelAdapter) Update(arg0 WardBusinessRel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataWardBusinessRelAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataWardBusinessRelAdapter)(nil).Update), arg0)
}
