// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package ordinance is a generated GoMock package.
package ordinance

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataOrdinanceAdapter is a mock of DataOrdinanceAdapter interface.
type MockDataOrdinanceAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataOrdinanceAdapterMockRecorder
}

// MockDataOrdinanceAdapterMockRecorder is the mock recorder for MockDataOrdinanceAdapter.
type MockDataOrdinanceAdapterMockRecorder struct {
	mock *MockDataOrdinanceAdapter
}

// NewMockDataOrdinanceAdapter creates a new mock instance.
func NewMockDataOrdinanceAdapter(ctrl *gomock.Controller) *MockDataOrdinanceAdapter {
	mock := &MockDataOrdinanceAdapter{ctrl: ctrl}
	mock.recorder = &MockDataOrdinanceAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataOrdinanceAdapter) EXPECT() *MockDataOrdinanceAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataOrdinanceAdapter) Create(arg0 *Ordinance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataOrdinanceAdapterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataOrdinanceAdapter)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDataOrdinanceAdapter) Delete(arg0 *Ordinance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataOrdinanceAdapterMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataOrdinanceAdapter)(nil).Delete), arg0)
}

// Read mocks base method.
func (m *MockDataOrdinanceAdapter) Read(arg0 *Ordinance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataOrdinanceAdapterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataOrdinanceAdapter)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockDataOrdinanceAdapter) ReadAll(arg0 *[]Ordinance, arg1 OrdinanceParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataOrdinanceAdapterMockRecorder) ReadAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataOrdinanceAdapter)(nil).ReadAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataOrdinanceAdapter) Update(arg0 Ordinance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataOrdinanceAdapterMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataOrdinanceAdapter)(nil).Update), arg0)
}
